rango/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from rango.views import IndexView, AboutView, ShowCategoryView, AddCategoryView
from rango.views import AddPageView, RestrictedView, PageSearchView
from rango.views import TrackUrlView, RegisterProfile 
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^add_category/$', login_required(AddCategoryView.as_view()),
        name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        ShowCategoryView.as_view(), name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        login_required(AddPageView.as_view()), name='add_page'),
    url(r'^restricted/$', login_required(RestrictedView.as_view()),
        name='restricted' ),
    url(r'^search/$', login_required(PageSearchView.as_view()), name='search'),
    url(r'^goto/$', TrackUrlView.as_view(), name='goto'),
    url(r'^register_profile/$', login_required(RegisterProfile.as_view()),
        name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page')
]

rango/models.py
from datetime import datetime

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):

    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.views = abs(self.views)
        super(Category, self).save(*args, **kwargs)

                   
    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Page(models.Model):

    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.PositiveIntegerField(default=0)
    first_visit=models.DateTimeField(auto_now_add=True)
    last_visit = models.DateTimeField()

    def save(self, *args, **kwargs):
        if self.last_visit > datetime.now():
            self.last_visit = datetime.now()
        super(Page, self).save(*args, **kwargs)
        
    
    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # Additional User attributes to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Return out something useful
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=
                           Category._meta.get_field('name').max_length,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=
                               Category._meta.get_field('views').default)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=
                               Category._meta.get_field('likes').default)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)


    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model.
        model = Category
        fields = ('name',)
        

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=
                            Page._meta.get_field('title').max_length,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=
                         Page._meta.get_field('url').max_length,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=
                               Page._meta.get_field('views').default)


    class Meta:
        # Provide an association between the ModelForm and a model.
        model = Page
        # Exclude the category field to hide the foreign key.
        exclude = ('category',)

    def clean(self):
        # Obtain the submitted url from a validated form
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url present and doesn't start with http,
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(),
                               help_text="Please enter a password.")
    username = forms.CharField(help_text="Please enter a username")
 

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

        
class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    
    class Meta:
        model = UserProfile
        exclude = ('user',)


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(
        attrs={'class':'form-control', 'size':'50'}),
        error_messages={'required': 'Please key in query then click search button'},
        label='')

rango/views.py
import inflection
from datetime import datetime

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseGone
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.views.generic import RedirectView


from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.forms import SearchForm
from rango.webhose_search import WebhoseMixin


class IndexView(TemplateView):    
    template_name = "rango/index.html"

    def get_context_data(self, **kwargs):
        # Test cookie to determine brower cookie support
        self.request.session.set_test_cookie()
        # Helper function to handle the cookies
        # Query db for first 5 categories with highest likes
        category_list = Category.objects.order_by('-likes')[:5]
        # Query db for first 5 pages with most views
        page_list = Page.objects.order_by('-views')[:5]
        # Create proxy object for the template context
        context = super(IndexView, self).get_context_data(**kwargs)
        # Add these lists to the context
        context['categories'] = category_list
        context['pages'] = page_list
        # Add the number of session visits to the context
        context['visits'] = self.visitor_cookie_handler(self.request)

        # Obtain response object
        return context

    # Site counter helper function
    def visitor_cookie_handler(self, request):
        # Use the COOKIES.get() function to obtain the visits cookie.
        # Cast the value returned to an integer or set the value to
        # 1 if the cookie doesn't exist.
        visits = int(self.get_server_side_cookie(request, 'visits', '1'))
        last_visit_cookie = self.get_server_side_cookie(request, 'last_visit',
                                                str(datetime.now()))
        last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                            '%Y-%m-%d %H:%M:%S')
        # if it's been more than a day since the last visit..
        if (datetime.now() - last_visit_time).seconds >= 86400:
            # Update the cookie visits count & last_visit time
            visits = visits + 1
            request.session['last_visit'] = str(datetime.now())
            # Set the last visit cookie
            request.session['last_visit'] = last_visit_cookie
            # Update/set the visits cookie
            request.session['visits'] = visits
        visits = inflection.ordinalize(visits)
        return visits
    
    # Helper function that asks the request for a cookie
    def get_server_side_cookie(self, request, cookie, default_val=None):
        val = request.session.get(cookie)
        if not val:
            val = default_val
        return val
   

class AboutView(TemplateView):    
    template_name = "rango/about.html"
    
    def get_context_data(self, **kwargs):
        if self.request.session.test_cookie_worked():
            print("TEST COOKIE WORKED!")
            self.request.session.delete_test_cookie()
        # Create proxy object for the template context
        context = super(AboutView, self).get_context_data(**kwargs)
        context['my_name'] = "TonyVEVO"
        return context
    

class ShowCategoryView(WebhoseMixin, TemplateView, FormView):
    template_name = "rango/category.html"
    model = Category, Page
    form_class = SearchForm
    
    def get_context_data(self, category_name_slug, **kwargs):
        try:
            category = Category.objects.get(slug=category_name_slug)
            pages = Page.objects.filter(category=category).order_by('-views')
        except Category.DoesNotExist:
            category = None
            pages = None
        kwargs['category'] = category
        kwargs['pages'] = pages        
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return kwargs
    
    def form_invalid(self, category_name_slug, query):
        return self.render_to_response(self.get_context_data(
            category_name_slug, form=query))

    def form_valid(self, category_name_slug, query):
        return self.render_search_response(self.get_context_data(
            category_name_slug, form=query))
        
    def post(self, request, *args, **kwargs):
        category_name_slug = kwargs['category_name_slug']
        query = self.get_form()
        if query.is_valid():
            return self.form_valid(category_name_slug, query)
        else:
            return self.form_invalid(category_name_slug, query)


class AddCategoryView(FormView):
    template_name = "rango/add_category.html"
    form_class = CategoryForm
    success_url = "/rango/"

    def form_valid(self, form):
        form.save(commit=True)
        # Direct the user back to the index page
        return super(AddCategoryView, self).form_valid(form)

    def form_invalid(self, form):
        # Print errors in the supplied form on the terminal
        print(form.errors)
        return super(AddCategoryView, self).form_invalid(form)

    
class AddPageView(FormView, TemplateView):     
    template_name = "rango/add_page.html"
    model = Page, Category
    form_class = PageForm

    def get_context_data(self, category_name_slug, **kwargs):
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None
        kwargs['category'] = category
        
        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        return kwargs

    def form_invalid(self, form, category_name_slug):
        return self.render_to_response(self.get_context_data(
            category_name_slug, form=form))        

    def form_valid(self, form, category_name_slug):
        page = form.save(commit=False)
        category = Category.objects.get(slug=category_name_slug)
        page.category = category
        page.first_visit = datetime.now()
        page.save()
        return HttpResponseRedirect(self.get_success_url(
            category_name_slug))
    
    def get_success_url(self, category_name_slug):
        self.success_url = "/rango/category/{}/".format(category_name_slug)
        if self.success_url:
            url = self.success_url
        else:
            raise improperlyConfigured(
                "No URL to redirect to. Provide a success URL"
                )
        return url

    def post(self, request, category_name_slug, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form, category_name_slug)
        else:
            return self.form_invalid(form, category_name_slug)      

            
class RestrictedView(TemplateView):
    template_name = "rango/restricted.html"
    def get_context_data(self, **kwargs):
        return super(RestrictedView, self).get_context_data(**kwargs)


class PageSearchView(FormView):
    form_class = SearchForm
    template_name = "rango/search.html"

    def get_context_data(self, query=None, **kwargs):
        context = {}
        context['form'] = self.get_form()
        if query:
            context['query'] = query
            context['result_list'] = self.get_queryset(query)
        return context
    
    def get_queryset(self, query):
        page_list = Page.objects.filter(title__icontains=query)
        queryset = []
        for page in page_list:
            queryset.append(page)
        self.queryset = queryset

        if self.queryset is None:
            if self.model:
                return self.model._default_manager.all()
            else:
                raise ImproperlyConfigured(
                    "%(cls)s is missing a QuerySet. Define "
                    "%(cls)s.model, %(cls)s.queryset, or override "
                    "%(cls)s.get_queryset()." % {
                        'cls': self.__class__.__name__
                        }
                    )
        return queryset
                
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        query = request.POST.get('query')
        return self.render_to_response(self.get_context_data(
            query=query, form=form))
    
    
class TrackUrlView(RedirectView):
    url = "/rango/"
    def get(self, request, *args, **kwargs):
        url = None
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views+=1
                page.save()
                url = page.url
            except:
                pass
        if url:
            if self.permanent:
                return http.HttpResponsePermanentRedirect(url)
            else:
                return HttpResponseRedirect(url)
        else:
            try:
                url = self.get_redirect_url(*args, **kwargs)
                return HttpResponseredirect(url)
            except:
                logger.warning(
                    'Gone: %s', request.path,
                    extra={'status_code':410, 'request': request}
                )
            return HttpResponseGone()
        
            
class RegisterProfile(FormView):
    form_class = UserProfileForm
    template_name = "rango/profile_registration.html"
    success_url = "/rango/"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@login_required
def profile(request, username):

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>

    <div>
        ...here is the about page!
    </div>

    <div>
        <img src="{{ MEDIA_URL }}cat.jpg"
                 alt="Picture of Cat" height="864" width="1296"/>
    </div>

    <div>
        <br />This demo has been put together by {{ my_name }}
    </div>
    <div>
    <button id="about-btn">
        Click Me - I'm JavaScript on Speed</button>
    <p>This is an example</p>
    <p>This is another example</p>
    </div>
    <div id="msg">
        Hello - I'm here for a JQuery Example too
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}

{% load bootstrap_toolkit %}
{% block title_block %}Add Category{% endblock %}
{% block body_block %}
    <form id="category_form" method="post" 
        action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading">Add a Category</a></h2>
    {% csrf_token %}
    {{ form|as_bootstrap }}<br />
    <br />
    <button class="btn btn-primary" type="submit"
        name="submit">Create Category</button>
    </form>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% load bootstrap_toolkit%}
{% block title %}Add Page{% endblock %}
{% block body_block %}
    {% if category %}
        <form role="form" id="page_form" method="post"
            action="/rango/category/{{category.slug}}/add_page/">
        <h2 class="form-signin-heading">Add a Page to 
            <a href="/rango/category/{{category.slug}}/">
            {{ category.name }}</a></h2>
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <br/>
        <button class="btn btn-primary"
                type="submit" name="submit">
            Add Page            
        </button>
        </form>
    {% else %}    
        <p>This category does not exist</p>
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,
                                   initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
        rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href=
           "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>
<body>


<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'rango:index' %}">
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">
                    About
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:restricted' %}">
                    Restricted Page
                </a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:search' %}">
                    Page Search
                </a>
            </li>
           <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                    Add a New Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">
                    Profile
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:list_profiles' %}">
                    List Profiles
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register'%}">
                    Register Here
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">
                    Login
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container-fluid">
    <div class="row">
		<div class="col-sm-3 col-md-2 sidebar">
			<div>
				<ul class="nav nav-list flex-column">
					<li class="nav-item">Type to find a category</li>
					<form>
						<li class="nav-item">
								<input class="search-query form-control" type="text"
									name="suggestion" value="" id="suggestion" />
						</li>
					</form>
				</ul>
			<hr>
			<div id="cats"></div>
			</div>	
		</div>
    <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
        {% block body_block %}{% endblock %}
    </div>
    </div>
</div>
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
    </script>
    <script
        src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
    </script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script
        src=
        "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
    </script>
<!-- JQuery/AJAX Reference -->
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js">
    </script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
	<script src="{% static "js/rango-ajax.js" %}"></script>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    <div>
    {% if category %}
        <h1>{{ category.name }}</h1>
        <div id="like_count">
        <strong>{{ category.likes }}</strong> people like this category
        {% if user.is_authenticated %}
            <button id="likes" data-catid="{{category.id}}"
                class="btn btn-primary btn-sm" type="button">
					Like
            </button>
        {% endif %}
        </div>
        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                {% if page.views > 1 %}
					<span class="badge badge-pill badge-primary">{{ page.views }} views</span>
                {% elif page.views == 1 %}
 					<span class="badge badge-pill badge-primary">{{ page.views }} view</span>
                {% endif %}
                </li>
            {% endfor %}
        {% else %}
            <strong>No pages currently in category.<br /></strong>
        {% endif %}
        {% if user.is_authenticated %}
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    </div>
    <div>
    <form class="form-inline" id="user_form" method="post" 
        action="{% url 'rango:show_category'  category.slug %}">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-primary" type="submit" name="submit"
            value="Search">Search Web</button>
    </form>        
    </div>
    <div>
        {% if search_list %}
        <h3>Results</h3>
        <!--Display search results in an ordered list -->
        <div class="list-group">
        {% for search_result in search_list %}
            <div class="list-group-item">
                <h4 class="list-group-item-heading">
                    <a href="{{ search_result.link }}" target="_blank">{{ search_result.title }}</a>
                </h4>
                <p class="list-group-item-text">{{ search_result.summary }}...</p>
				<div class="rango-add">
					<button data-catid="{{ category.id }}" data-title="{{ search_result.title }}"
						data-url="{{ search_result.link }}"
							class="rango-add btn btn-info btn-sm" type="button">Add page</button>
				</div>
            </div>
        {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/rango/cats.html
<ul>
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
            <li>
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>    
            </li>
        {% else %}    
            <li>    
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>No categories present for that search.</strong></li>
{% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    {% if user.is_authenticated %}
        <h1>hey there {{ user.username }}!</h1>
    {% else %}
        <h1>hey there partner!</h1>
    {% endif %}
    </div>
    <div class="row marketing">
        <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li><a href="{% url 'rango:show_category' category.slug %}">
                {{ category.name }}</a>
				<span class="badge badge-pill badge-primary">{{ category.likes }} likes</span>
			</li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}   
    </div>
    </p>
    </div>
    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a>
				<span class="badge badge-pill badge-primary">{{ page.views }} views</span>
			</li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" height="768" width="1024" />
    <div>
	<br />This is your {{ visits }} day visiting this page!
    </div>     
</div>


{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}User Profiles{% endblock %}

{% block body_block %}
<h1>User Profiles</h1>

<div class="panel">
    {% if userprofile_list %}
    <div class="panel-heading">
        <!--Display search results in an ordered list-->
        <div class="panel-body">
            <div class="list-group">
                {% for listuser in userprofile_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{% url 'rango:profile' listuser.user.username %}">
                             {{ listuser.user.username }}</a>
                        {% if listuser.picture %}
                        <img src="{{ MEDIA_URL }}{{ listuser.picture }}"
                             width="64" height="64">
                         {% else %}
                        <img src="http://lorempixel.com/64/64/people/"
                             width="64" height="64">
                        {% endif %}                     
                    </h4>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
        <p>There are no users for the site.</p>
    {% endif %}
</div>
{% endblock %}

templates/rango/page_list.html
{% if pages %}
<ul>
	{% for page in pages %}
	<li><a href="{% url 'goto' %}?page_id={{page.id}}"\>{{ page.title }}</a></li>
	{% endfor %}
</ul>
{% else %}
	<strong>No pages currently in category.</strong>
{% endif %}

templates/rango/profile.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}{{ selecteduser.username }}Profile{% endblock %}

{% block body_block %}
<h1>{{selecteduser.username}}Profile</h1>
<img src="{{ MEDIA_URL }}{{ userprofile.picture }}"
    width="300"
    height="300"
    alt="{{ selecteduser.username }}" />
<br />
<div>
    {% if selecteduser.username == user.username %}
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
        </form>
    {% else %}
    <p><strong>Website:</strong><a href="{{ userprofile.website }}">
        {{ userprofile.website }} </a></p>
    {% endif %}
</div>
<div id="edit_profile"></div>
{% endblock %}

templates/rango/profile_registration.html
{% extends "rango/base.html" %}

{% block title_block %}
    Registration - Step 2
{% endblock %}

{% block body_block %}
    <h1>Registration - Step 2</h2>
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html'%}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text.
{% endblock %}
    

templates/rango/search.html
{% extends 'rango/base.html' %}

{% load staticfiles %}
{% block title_block %} Search {% endblock %}

{% block body_block %}
<div>
    <br />
    <h2>Search for page in Categories</h2>
    <br/>
    <form class="form-inline"  role='form' id="search_form" 
	method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}
        {% for field in form %}
	    <div>
		{{ field }}{{ field.errors }}
		{% if field.help_text %}
		    {{ field.help_text }}
		{% endif %}
	    </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit" name="submit"
                value="Search">Find Page</button>
    </form>
    <div>
    {% if result_list %}
        <h3>Results</h3>
        <!--Display search results in an ordered list -->
        <div class="list-group">
        {% for page in result_list %}
            <div class="list group-item">
                <h4 class="list-group-item-heading">
                    <a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                </h4>
            </div>
        {% endfor %}
        </div>
    {% endif %}
    </div>    
</div>
{% endblock%}